/** UI copy, EN + IT. Italian carries its accents; no em dashes. */
const STRINGS = {
  en: {
    consentTitle: 'Keep My Prompts',
    consentBody: 'Save the prompts you send here to your library? Only what you type, never the replies. You can pause any time from the extension icon.',
    consentYes: 'Yes, save them',
    consentNo: 'Not on this site',
    scoring: 'Scoring…',
    saving: 'Saving…',
    score: 'Prompt Score',
    tip: 'Tip',
    improve: 'Improve this prompt',
    optimizing: 'Optimizing…',
    replace: 'Replace in composer',
    saveVersion: 'Save as version',
    close: 'Close',
    saved: 'Saved to your library',
    reused: (n: number) => `Reused ${n} times`,
    atLimit: (max: number) => `Library full (${max}/${max}). Upgrade to Pro to keep saving.`,
    upgrade: 'Upgrade',
    alreadyOptimal: 'Already optimal: no better variant found.',
    dailyLimit: 'Daily Quick Optimize limit reached.',
    notConnected: 'Connect the extension to your Keep My Prompts account from the extension icon.',
    error: 'Something went wrong. Try again in a moment.',
    variantTitle: 'Optimized variant',
    applied: 'Composer updated and saved to your library',
    versionSaved: 'Saved as a new version',
    evaluate: 'Score prompt',
    saveToLibrary: 'Save to library',
    optimize: 'Optimize',
    alreadyGood: 'Already good: optimizing would spend a Quick Optimize for little gain.',
    replacedLocal: 'Composer updated. Send it, or save it to your library.',
    tooShort: 'Write at least 10 words to score',
    remainingQuick: (n: number) => `${n} Quick Optimize left today`,
    collapse: 'Hide',
    expand: 'Keep My Prompts',
    alreadyScored: 'Already scored. Edit the text to score again.',
    criteria: { clarity: 'Clarity', context: 'Context', tcof: 'TCOF structure', rolePrompting: 'Role', fewShot: 'Examples', chainOfThought: 'Step-by-step reasoning', behavioralClarity: 'Behavioral clarity', constraintCoverage: 'Constraint coverage', personaTone: 'Persona and tone' } as Record<string, string>,
  },
  it: {
    consentTitle: 'Keep My Prompts',
    consentBody: 'Salvare nella tua libreria i prompt che invii qui? Solo quello che scrivi tu, mai le risposte. Puoi mettere in pausa quando vuoi dall’icona dell’estensione.',
    consentYes: 'Sì, salvali',
    consentNo: 'Non su questo sito',
    scoring: 'Valutazione in corso…',
    saving: 'Salvataggio…',
    score: 'Prompt Score',
    tip: 'Consiglio',
    improve: 'Migliora questo prompt',
    optimizing: 'Ottimizzazione in corso…',
    replace: 'Sostituisci nella casella',
    saveVersion: 'Salva come versione',
    close: 'Chiudi',
    saved: 'Salvato nella tua libreria',
    reused: (n: number) => `Riusato ${n} volte`,
    atLimit: (max: number) => `Libreria piena (${max}/${max}). Passa a Pro per continuare a salvare.`,
    upgrade: 'Passa a Pro',
    alreadyOptimal: 'Già ottimale: nessuna variante migliore trovata.',
    dailyLimit: 'Limite giornaliero di Quick Optimize raggiunto.',
    notConnected: 'Collega l’estensione al tuo account Keep My Prompts dall’icona dell’estensione.',
    error: 'Qualcosa è andato storto. Riprova tra un momento.',
    variantTitle: 'Variante ottimizzata',
    applied: 'Casella aggiornata e prompt salvato nella libreria',
    versionSaved: 'Salvato come nuova versione',
    evaluate: 'Valuta prompt',
    saveToLibrary: 'Salva in libreria',
    optimize: 'Ottimizza',
    alreadyGood: 'Già buono: ottimizzarlo spenderebbe una Quick Optimize per poco.',
    replacedLocal: 'Casella aggiornata. Invialo, oppure salvalo nella libreria.',
    tooShort: 'Scrivi almeno 10 parole per valutare',
    remainingQuick: (n: number) => `${n} Quick Optimize rimaste oggi`,
    collapse: 'Nascondi',
    expand: 'Keep My Prompts',
    alreadyScored: 'Già valutato. Modifica il testo per valutarlo di nuovo.',
    criteria: { clarity: 'Chiarezza', context: 'Contesto', tcof: 'Struttura TCOF', rolePrompting: 'Ruolo', fewShot: 'Esempi', chainOfThought: 'Ragionamento passo passo', behavioralClarity: 'Chiarezza comportamentale', constraintCoverage: 'Copertura dei vincoli', personaTone: 'Persona e tono' } as Record<string, string>,
  },
} as const

export type Locale = keyof typeof STRINGS
export type Strings = (typeof STRINGS)['en']

export function t(locale: Locale): Strings {
  return STRINGS[locale] as Strings
}
